import { View, type StyleProp, type ViewProps } from 'react-native';

import { depthWhen, useTheme } from '@/theme';

import type { LayoutStyle } from './layoutStyle';

export type CardVariant = 'default' | 'elevated' | 'outlined' | 'inset';
export type CardPadding = 'sm' | 'md' | 'lg' | 'xl';

const PADDING = { sm: 2, md: 4, lg: 6, xl: 8 } as const;

export interface CardProps extends Omit<ViewProps, 'style'> {
  /**
   * `default`: a filled surface resting on the page.
   * `elevated`: floats above the page (a shadow; a lighter surface in dark mode).
   * `outlined`: the same, with a visible border. Good for lists.
   * `inset`: a well pressed into the page, for grouped details. Clean shows it as a quiet band; Soft presses it in.
   * Clean and Soft draw these differently from the same roles (see `depth` in the theme).
   */
  variant?: CardVariant;
  /** `sm` 8pt, `md` 16pt (default), `lg` 24pt, `xl` 32pt. */
  padding?: CardPadding;
  /** `ai` marks content generated by AI: a violet tint and edge, so it is always recognisable. */
  tone?: 'default' | 'ai';
  /** Show the pressed look. Set by interactive wrappers, not by hand. */
  pressed?: boolean;
  /** Layout only (margin, flex). Colour, radius and border come from tokens. */
  style?: StyleProp<LayoutStyle>;
}

/** A themed container for grouping related content. */
export function Card({ variant = 'default', padding = 'md', tone = 'default', pressed = false, style, ...rest }: CardProps) {
  const { colors, radius, space, depth, borderWidth } = useTheme();
  const ai = tone === 'ai';
  const inset = variant === 'inset';
  const base = ai ? colors.ai.subtle : inset ? colors.background.secondary : variant === 'elevated' ? colors.surface.elevated : colors.surface.primary;
  const resting = inset ? depth.field : variant === 'elevated' ? depth.floating : depth.surface;

  return (
    <View
      style={[
        {
          padding: space[PADDING[padding]],
          borderRadius: radius.lg,
          backgroundColor: pressed ? colors.surface.pressed : base,
          borderWidth: variant === 'outlined' || ai ? borderWidth.thin : borderWidth.none,
          borderColor: ai ? colors.ai.border : colors.border.default,
        },
        depthWhen(pressed, resting, depth),
        style,
      ]}
      {...rest}
    />
  );
}
