import { useRouter } from 'expo-router';
import { useState } from 'react';

import { Banner, Button, Card, Screen, Stack, Text } from '@/components/core';
import { ConfidenceIndicator } from '@/components/ai';
import { InsightCard, MoneyRangeText } from '@/components/fintech';
import { money } from '@/utils/money';

/**
 * PATTERN: proactive AI insights. Every insight is labelled as AI, explains itself on request,
 * collects feedback with reasons, and can be dismissed or turned off. The forecast is a range.
 */
type InsightId = 'dining' | 'balance' | 'subscriptions';
const usd = (minor: number) => money(minor, 'USD');

export default function Insights() {
  const router = useRouter();
  const [dismissed, setDismissed] = useState<InsightId[]>([]);
  const [turnedOff, setTurnedOff] = useState<InsightId[]>([]);
  const [lastFeedback, setLastFeedback] = useState<string | null>(null);

  const visible = (id: InsightId) => !dismissed.includes(id) && !turnedOff.includes(id);
  const dismiss = (id: InsightId) => setDismissed((previous) => [...previous, id]);
  const turnOff = (id: InsightId) => setTurnedOff((previous) => [...previous, id]);

  return (
    <Screen>
      <Stack gap={5}>
        <Text variant="heading1">Insights</Text>

        <Banner tone="ai" title="Insights are generated by AI" action={{ label: 'AI and data controls', onPress: () => router.push('/ai-settings') }}>
          They use your transaction history to spot patterns. You can change what they use, or turn them off.
        </Banner>

        <Card variant="outlined" padding="lg">
          <Stack gap={3}>
            <Text variant="heading3">Projected balance on Oct 31</Text>
            <MoneyRangeText variant="moneyLarge" low={usd(118000)} high={usd(134000)} />
            <ConfidenceIndicator level="medium" />
            <Text variant="bodySmall" color="secondary">
              Based on your usual income and bills. Large one-off purchases would change it.
            </Text>
          </Stack>
        </Card>

        {visible('dining') ? (
          <InsightCard
            title="Dining is up 23% this month"
            summary="You've spent more on restaurants than your usual pattern."
            amount={usd(41260)}
            why={{
              dataUsed: ['Checking •••• 4821, last 90 days'],
              factors: ['14 restaurant purchases this month (usual: 9)', 'Your three largest were on weekends'],
            }}
            action={{ label: 'Set a dining budget', onPress: () => undefined }}
            onDismiss={() => dismiss('dining')}
            onFeedback={(feedback) => setLastFeedback(JSON.stringify(feedback))}
            onChangeData={() => router.push('/ai-settings')}
            onTurnOff={() => turnOff('dining')}
          />
        ) : null}

        {visible('balance') ? (
          <InsightCard
            title="Your balance may run low around Oct 28"
            summary="Rent is due the same week as a gap between paychecks."
            range={{ low: usd(31000), high: usd(52000) }}
            confidence="medium"
            why={{
              dataUsed: ['Checking •••• 4821 balance', 'Recurring bills, last 6 months'],
              factors: ['Rent ($1,850) due Oct 28', 'Paychecks usually arrive on the 1st and 15th'],
            }}
            action={{ label: 'Move money from Savings', onPress: () => undefined }}
            onDismiss={() => dismiss('balance')}
            onFeedback={(feedback) => setLastFeedback(JSON.stringify(feedback))}
            onChangeData={() => router.push('/ai-settings')}
            onTurnOff={() => turnOff('balance')}
          />
        ) : null}

        {visible('subscriptions') ? (
          <InsightCard
            title="Two video subscriptions overlap"
            summary="You pay for two streaming services every month."
            why={{
              dataUsed: ['Recurring payments, last 6 months'],
              factors: ['Netflix $22.99 and another video service $15.99, both monthly'],
            }}
            action={{ label: 'Review subscriptions', onPress: () => undefined }}
            onDismiss={() => dismiss('subscriptions')}
            onFeedback={(feedback) => setLastFeedback(JSON.stringify(feedback))}
            onChangeData={() => router.push('/ai-settings')}
            onTurnOff={() => turnOff('subscriptions')}
          />
        ) : null}

        {turnedOff.length ? (
          <Banner tone="success" title="Got it. You won't see those insights.">
            You can turn them back on in AI and data controls.
          </Banner>
        ) : null}

        {lastFeedback ? (
          <Text variant="caption" color="secondary">
            {`ai_feedback_submitted ${lastFeedback}`}
          </Text>
        ) : null}

        {visible('dining') || visible('balance') || visible('subscriptions') ? null : (
          <Stack gap={2} align="start">
            <Text color="secondary">No insights right now.</Text>
            <Button
              label="Show them again (demo)"
              variant="secondary"
              onPress={() => {
                setDismissed([]);
                setTurnedOff([]);
              }}
            />
          </Stack>
        )}
      </Stack>
    </Screen>
  );
}
